### ISSUE TITLE
Disable hardtime on vimshell

### ISSUE THREAD

**Issue by ZzAntares** [takac/vim-hardtime#28]
Hello, such a great plugin over here, I'm trying to disable hardtime on the vimshell buffers but I can not make it to work, I've tried this with no success:

```
let g:hardtime_ignore_buffer_patterns = ["NERD.*", "*vimshell*"]
let g:hardtime_ignore_buffer_patterns = ["NERD.*", "vimshell"]
let g:hardtime_ignore_buffer_patterns = ["NERD.*", "vimshell*"]
```

On vim-shell buffer name appears as `[vimshell] - default` and filetype is `vimshell`.

Thanks in advance!

**Comment by takac** [comment]
Not reproducible. 

hardtime_ignore_buffer_patterns only works in conjunction with hardtime_default_on. You can still toggle hardtime on and off per buffer with :HardTimeOn and :HardTimeOff and this will not if the  buffer is in the ignore list. This is expected behaviour.

**Comment by ZzAntares** [comment]
Hello @takac, what I'm asking is the correct way to ignore a vimshell buffer from hardtime, since putting it in the `hardtime_ignore_buffer_patterns` does not work. And yes I've enabled hard time on startup via `let g:hardtime_default_on=1`.

Thanks

**Comment by takac** [comment]
I couldn't reproduce the issue. I set `let g:hardtime_ignore_buffer_patterns = ["NERD.*", "vimshell"]` and that worked.
