### ISSUE TITLE
Disable temporarily for casual code browsing/reading

### ISSUE THREAD

**Issue by nemanjan00** [takac/vim-hardtime#59]
Are there any ways to temporarily disable this plugin, for casual browsing and reading code. 

Or any recommended ways to do it?

**Comment by ben-turner** [comment]
Add this to your vimrc:

    nnoremap <leader>h :HardTimeToggle<cr>

Then you can quickly toggle it with `\h` (or whatever your leader key is instead of `\`)

**Comment by nemanjan00** [comment]
Thanks a lot! :D
