### ISSUE TITLE
Completely disallow some keys, while allowing single occurances of some keys

### ISSUE THREAD

**Issue by spagy** [takac/vim-hardtime#60]
It would be great if you could completely disallow some keys (e.g. arrow keys) while allowing some other keys (e.g. hjkl) only once or twice.

As far as I can tell, if I want to allow hjkl for one or two presses then I also have to allow arrow keys for the one or two presses.

**Comment by vegerot** [comment]
Like
```
    let g:hardtime_default_on = 1
    let g:list_of_disabled_keys = ["<UP>", "<DOWN>", "<LEFT>", "<RIGHT>"]
    let g:hardtime_maxcount = 2
```
?

**Comment by spagy** [comment]
yep that seems to work perfectly, i think i'd misunderstood what some of the config options did

**Comment by vegerot** [comment]
No problem.  TBH the documentation is kinda bad.  I copied my config, and probably wouldn't have known what to do either if it weren't for that
